local AddonName, a = ...
a.Localize = setmetatable({}, {__index = function(_, key) return key end})
local L = a.Localize

L["Guild invite key hint"] =
	"Keybind: create a macro with |cffffffff/mgtginvite|r, put it on an action bar, then bind a key to that slot."

L["Tip line"] = "Tip me golds on |cFFFF69B4Kirbybank-Soulseeker|r"
L["Add Guild Member"] = "Add Guild Member"
L["You are not in a guild."] = "You are not in a guild."
L["You don't have permission to invite guild members."] = "You don't have permission to invite guild members."
L["Add guild notes when available"] = "Add guild notes when available"
L["Note:"] = "Note:"
L["Officer:"] = "Officer:"
L["Tabard Stalker"] = "Tabard Stalker"
L["Tabard scan (party/raid)"] = "Tabard scan (party/raid)"
L["Scan group tabards"] = "Scan group tabards"
L["Reset tabard data"] = "Reset tabard data"
L["Ready to scan your party or raid."] = "Ready to scan your party or raid."
L["Join a party or raid to scan tabards."] = "Join a party or raid to scan tabards."
L["Inspecting %d/%d: %s"] = "Inspecting %d/%d: %s"
L["Inspecting %d/%d..."] = "Inspecting %d/%d..."
L["Tabard scan complete. Everyone has a tabard!"] = "Tabard scan complete. Everyone has a tabard!"
L["Tabard scan complete. Announcing missing tabards..."] = "Tabard scan complete. Announcing missing tabards..."
L["Tabard cache cleared."] = "Tabard cache cleared."
L["You must be in a party or raid."] = "You must be in a party or raid."
L["No group members need a tabard scan."] = "No group members need a tabard scan."
L["Scan finished."] = "Scan finished."
L["Scan finished. %d without tabard."] = "Scan finished. %d without tabard."
L["Tabard scan complete. %d without tabard (see chat)."] = "Tabard scan complete. %d without tabard (see chat)."
L["Click Announce in /say to speak in game."] = "Click Announce in /say to speak in game."
L["Announce missing tabards in /say"] = "Announce missing tabards in /say"
L["Cannot announce in combat."] = "Cannot announce in combat."
L["Announced missing tabards in /say."] = "Announced missing tabards in /say."
L["Only for guildies"] = "Only for guildies"
L["Minimum level:"] = "Minimum level:"
L["Auto scan when grouping"] = "Auto scan when grouping"
L["%s is too far away or cannot be inspected."] = "%s is too far away or cannot be inspected."
L["Will retry inspection when in range (auto scan)."] = "Will retry inspection when in range (auto scan)."
L["Scan finished. %d not inspectable."] = "Scan finished. %d not inspectable."
L["Scan finished. %d without tabard, %d not inspectable."] = "Scan finished. %d without tabard, %d not inspectable."

-- English: keys are used as labels (metatable fallback).
-- French:
if GetLocale() == "frFR" then
	L["Font size changed to"] = "La taille de la police a été changée en"
	L["MyGuildTools"] = "Outils de guilde"
	L["Tooltip"] = "Info-bulle"
	L["Information unavailable"] = "Information non disponible"
	L["Select One"] = "Choisissez-en un"
	L["Show guild rank in tooltips"] = "Afficher le rang de guilde dans les info-bulles"
	L["Show healthbar under player tooltips"] = "Afficher la barre de santé sous les info-bulles des joueurs"
	L["Show player realms in tooltips"] = "Afficher les royaumes des joueurs dans les info-bulles"
	L["Show player titles in tooltips"] = "Afficher les titres des joueurs dans les info-bulles"
	L["Show rank after guild name"] = "Afficher le rang après le nom de guilde"
	L["Target out of range"] = "Cible hors de portée"
	L["Tooltip font size:"] = "Taille de la police de l'info-bulle:"
	L["Use colours"] = "Utilisez des couleurs"
	L["Guild Invite"] = "Invitation de guilde"
	L["Add a right-click menu to /ginvite"] = "Ajouter un menu contextuel pour /ginvite"
	L["Guild invite key hint"] = "Raccourci : créez une macro avec |cffffffff/mgtginvite|r, placez-la sur une barre d'action, puis assignez une touche à cet emplacement."
	L["Tip line"] = "Offrez moi de l'or sur |cFFFF69B4Kirbybank-Soulseeker|r"
	L["Add Guild Member"] = "Ajouter un membre de guilde"
	L["You are not in a guild."] = "Vous n'êtes pas dans une guilde."
	L["You don't have permission to invite guild members."] = "Vous n'avez pas le droit d'inviter des membres en guilde."
	L["Add guild notes when available"] = "Ajouter les notes de guilde si disponibles"
	L["Note:"] = "Note :"
	L["Officer:"] = "Officier :"
	L["Tabard Stalker"] = "Traqueur de tabard"
	L["Tabard scan (party/raid)"] = "Scan du groupe ou du raid (tabards)"
	L["Scan group tabards"] = "Scanner les tabards du groupe"
	L["Reset tabard data"] = "Réinitialiser données tabard"
	L["Ready to scan your party or raid."] = "Prêt à scanner le groupe ou le raid."
	L["Join a party or raid to scan tabards."] = "Rejoignez un groupe ou un raid pour scanner les tabards."
	L["Inspecting %d/%d: %s"] = "Inspection %d/%d : %s"
	L["Inspecting %d/%d..."] = "Inspection %d/%d..."
	L["Tabard scan complete. Everyone has a tabard!"] = "Scan terminé. Tout le monde porte un tabard !"
	L["Tabard scan complete. Announcing missing tabards..."] = "Scan terminé. Annonce des tabards manquants..."
	L["Tabard cache cleared."] = "Cache tabard effacé."
	L["You must be in a party or raid."] = "Vous devez être en groupe ou en raid."
	L["No group members need a tabard scan."] = "Aucun membre à scanner (tous en cache ou absents)."
	L["Scan finished."] = "Scan terminé."
	L["Scan finished. %d without tabard."] = "Scan terminé. %d sans tabard."
	L["Tabard scan complete. %d without tabard (see chat)."] = "Scan terminé. %d sans tabard (voir le chat)."
	L["Click Announce in /say to speak in game."] = "Cliquez sur Annoncer en /say pour parler en jeu."
	L["Announce missing tabards in /say"] = "Annoncer les tabards manquants en /say"
	L["Cannot announce in combat."] = "Impossible d'annoncer en combat."
	L["Announced missing tabards in /say."] = "Tabards manquants annoncés en /say."
	L["Only for guildies"] = "Guilde uniquement"
	L["Minimum level:"] = "Niveau minimum :"
	L["Auto scan when grouping"] = "Scan auto à l'arrivée en groupe"
	L["%s is too far away or cannot be inspected."] = "%s est trop loin ou ne peut pas être inspecté."
	L["Will retry inspection when in range (auto scan)."] = "Nouvelle tentative d'inspection à portée (scan auto)."
	L["Scan finished. %d not inspectable."] = "Scan terminé. %d non inspectable(s)."
	L["Scan finished. %d without tabard, %d not inspectable."] = "Scan terminé. %d sans tabard, %d non inspectable(s)."
end
